### ISSUE TITLE
Anissa_solution

### ISSUE THREAD

**Issue by iamanissa** [ga-wdi-exercises/final-countdown#52]
I tried adding a class of fail if my variable was 0 or less.
I expected 0 to turn red to happen.
1 and 0 turned red instead.
My repo link is 
repo: https://github.com/SuperJones/final-countdown/blob/anissa_solution/index.html and my question is about lines 75-78 (I think).

**Comment by RobertAKARobin** [comment]
Hey, Anissa! We only do issue-based support on projects. If you have a question, ask an instructor during the day — or another student!
